version: '3.8'

services:
  app:
    build: .
    container_name: memory-guard-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/memory_guard?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=memoryguard

      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

      - spring.jpa.hibernate.ddl-auto=update
      - jwt.secret=V29vYWNvdXJzZUhvbWV3b3JrU2VjcmV0S2V5Rm9ySldUU2FtcGxlMQ==
      - jwt.access-token-expiration-millis=9000000
      - jwt.refresh-token-expiration-millis=604800000
      - jwt.refresh-token-expiration-seconds=604800
    restart: always

  db:
    image: mysql:8.0
    container_name: memory-guard-db
    environment:
      - mysql.root.password=memoryguard
      - mysql.database=memory_guard
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: